### ISSUE TITLE
Update the navigation Bar with 6 tabs

### ISSUE THREAD

**Issue by RohitB97** [RohitB97/saarang-hybrid-app#1]
@shafeef901 Update the navigation bar ....add 6 tabs..but display only 5 (login/settings).....and create corresponding pages and make them blank....remove the current pages ( if you want to keep some code for future use...then comment it out)

**Comment by shafeef901** [comment]
Acknowledged!

**Comment by shafeef901** [comment]
Back button for various Pages in the side navigation bar is not there. Bottom tab navigation to be removed too.

**Comment by RohitB97** [comment]
fix it soon ....and put an update here @shafeef901

**Comment by shafeef901** [comment]
Fixed it!
